name: Tests

on:
  push:
    branches:
      - main
    paths:
      - "pkg/**"
  pull_request:
    branches: -main
    paths:
      - "pkg/**"
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.1
          cache: false

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...
